# Generated by Django 4.0.3 on 2023-06-22 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=30)),
                ('listing_description', models.TextField(max_length=300)),
                ('listing_make', models.CharField(choices=[('IPHONE', 'Iphone'), ('SAMSUNG', 'Samsung'), ('HUAWEI', 'Huawei'), ('HTC', 'Htc'), ('LG', 'LG'), ('NOKIA', 'Nokia'), ('BLACKVIEW', 'Blackview'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('listing_model', models.CharField(max_length=20)),
                ('listing_color', models.CharField(max_length=30)),
                ('listing_internal_memory', models.CharField(choices=[('8GB', '8Gb'), ('16GB', '16Gb'), ('32GB', '32Gb'), ('64GB', '64Gb'), ('128GB', '128Gb'), ('256GB', '256Gb'), ('512GB', '512Gb'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('listing_ram', models.CharField(choices=[('1GB', '1Gb'), ('2GB', '2Gb'), ('3GB', '3Gb'), ('4GB', '4Gb'), ('6GB', '6Gb'), ('8GB', '8Gb'), ('12GB', '12Gb'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('listing_condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], default='USED', max_length=20)),
                ('listing_price', models.IntegerField()),
                ('listing_image', models.ImageField(blank=True, null=True, upload_to='images/listing/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_first_name', models.CharField(max_length=50)),
                ('profile_last_name', models.CharField(max_length=50)),
                ('profile_date_of_birth', models.DateField()),
                ('profile_phone_number', models.CharField(max_length=9)),
                ('profile_email', models.EmailField(max_length=254)),
                ('profile_password', models.CharField(max_length=70)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('profile_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_on_name', models.CharField(max_length=30)),
                ('order_on_surname', models.CharField(max_length=40)),
                ('order_on_city', models.CharField(max_length=40)),
                ('order_on_municipality', models.CharField(max_length=40)),
                ('order_delivery_address', models.CharField(max_length=30)),
                ('order_delivery_address1', models.CharField(max_length=30)),
                ('order_phone_number', models.CharField(max_length=9)),
                ('order_cc_number', models.CharField(max_length=16)),
                ('order_cc_holder', models.CharField(max_length=40)),
                ('order_cc_date', models.CharField(max_length=5)),
                ('order_cc_cvv', models.CharField(max_length=3)),
                ('order_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileSellingApp.mobilelisting')),
                ('order_profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='MobileSellingApp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='mobilelisting',
            name='listing_profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='MobileSellingApp.profile'),
        ),
    ]
