# Generated by Django 4.2.1 on 2023-06-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileSellingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilelisting',
            name='listing_color',
            field=models.CharField(max_length=30, verbose_name='Боја'),
        ),
        migrations.AlterField(
            model_name='mobilelisting',
            name='listing_condition',
            field=models.CharField(choices=[('NEW', 'Користен'), ('USED', 'Нов')], default='USED', max_length=20, verbose_name='Состојба'),
        ),
        migrations.AlterField(
            model_name='mobilelisting',
            name='listing_description',
            field=models.TextField(max_length=300, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='mobilelisting',
            name='listing_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/listing/', verbose_name='Слика'),
        ),
        migrations.AlterField(
            model_name='mobilelisting',
            name='listing_internal_memory',
            field=models.CharField(choices=[('8GB', '8Gb'), ('16GB', '16Gb'), ('32GB', '32Gb'), ('64GB', '64Gb'), ('128GB', '128Gb'), ('256GB', '256Gb'), ('512GB', '512Gb'), ('OTHER', 'Останато')], default='OTHER', max_length=20, verbose_name='Внатрешна меморија'),
        ),
        migrations.AlterField(
            model_name='mobilelisting',
            name='listing_make',
            field=models.CharField(choices=[('IPHONE', 'Iphone'), ('SAMSUNG', 'Samsung'), ('HUAWEI', 'Huawei'), ('HTC', 'Htc'), ('LG', 'LG'), ('NOKIA', 'Nokia'), ('BLACKVIEW', 'Blackview'), ('OTHER', 'Останато')], default='OTHER', max_length=20, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='mobilelisting',
            name='listing_model',
            field=models.CharField(max_length=20, verbose_name='Модел'),
        ),
        migrations.AlterField(
            model_name='mobilelisting',
            name='listing_price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='mobilelisting',
            name='listing_ram',
            field=models.CharField(choices=[('1GB', '1Gb'), ('2GB', '2Gb'), ('3GB', '3Gb'), ('4GB', '4Gb'), ('6GB', '6Gb'), ('8GB', '8Gb'), ('12GB', '12Gb'), ('OTHER', 'Останато')], default='OTHER', max_length=20, verbose_name='РАМ меморија'),
        ),
        migrations.AlterField(
            model_name='mobilelisting',
            name='listing_title',
            field=models.CharField(max_length=30, verbose_name='Наслов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_date_of_birth',
            field=models.DateField(verbose_name='Дата на раѓање'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_email',
            field=models.EmailField(max_length=254, verbose_name='Е-маил'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_first_name',
            field=models.CharField(max_length=50, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/', verbose_name='Слика'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_last_name',
            field=models.CharField(max_length=50, verbose_name='Презиме'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_password',
            field=models.CharField(max_length=70, verbose_name='Лозинка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_phone_number',
            field=models.CharField(max_length=9, verbose_name='Телефонски број'),
        ),
    ]
